### ISSUE TITLE
🚀 高優先度: CI/CD依存関係インストール時間最適化 - GitHubキャッシュ機能実装

### ISSUE THREAD

**Issue by nyasuto** [nyasuto/moz#25]
### **優先度: 高**

**影響:** CI/CD実行時間の大幅増加（推定2-3分の無駄時間）
**コンポーネント:** GitHub Actions ワークフロー  
**ファイル:** `.github/workflows/ci.yml`

### 問題の説明

現在のCI/CDパイプラインでは、依存関係のインストールが毎回フルインストールされており、実行時間を支配している。

**具体的な問題:**

1. **Go依存関係の重複インストール**
   - 各ジョブで `make install` が `go mod download` を毎回実行
   - `golangci-lint`, `gosec`, `govulncheck` を毎回ダウンロード・インストール
   - 推定時間: 1-2分/ジョブ

2. **システムパッケージの重複インストール**
   - `sudo apt-get install` が複数ジョブで重複実行
   - `shellcheck`, `jq`, `bc` などを毎回インストール
   - 推定時間: 30秒-1分/ジョブ

3. **Go言語環境の重複セットアップ**
   - Go 1.21.0のダウンロード・インストールを毎回実行
   - 推定時間: 1分/ジョブ

**影響分析:**
```yaml
ジョブ数: 6個 (quality-checks, performance-tests, etc.)
無駄時間/ジョブ: 2-4分
総無駄時間: 12-24分/CI実行
```

### 推奨解決策

**1. Go言語環境キャッシュ**
```yaml
- name: 🐹 Go言語セットアップ
  uses: actions/setup-go@v5
  with:
    go-version: '1.21.0'
    cache: true
    cache-dependency-path: go.sum
```

**2. Go依存関係キャッシュ**
```yaml
- name: 📦 Go依存関係キャッシュ
  uses: actions/cache@v4
  with:
    path: |
      ~/go/pkg/mod
      ~/.cache/go-build
    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    restore-keys: |
      ${{ runner.os }}-go-
```

**3. Goツールバイナリキャッシュ**
```yaml
- name: 🛠️ Goツールキャッシュ
  uses: actions/cache@v4
  with:
    path: ~/go/bin
    key: ${{ runner.os }}-go-tools-${{ hashFiles('Makefile') }}
    restore-keys: |
      ${{ runner.os }}-go-tools-
```

**4. システムパッケージキャッシュ**
```yaml
- name: 📦 APTパッケージキャッシュ
  uses: awalsh128/cache-apt-pkgs-action@latest
  with:
    packages: shellcheck jq bc
    version: 1.0
```

### 受け入れ基準

- [ ] 各ジョブでのGo環境セットアップ時間が30秒以下になる
- [ ] Go依存関係ダウンロード時間が初回以降10秒以下になる
- [ ] システムパッケージインストール時間が初回以降5秒以下になる
- [ ] 全CI実行時間が50%以上短縮される
- [ ] キャッシュミス時も正常に動作する

**プロジェクトへの価値説明**
CI/CD実行時間の大幅短縮により、開発者の生産性向上とGitHub Actionsの使用時間削減によるコスト最適化を実現。特にPR作成時の待ち時間を大幅に短縮し、開発フローの改善に貢献する。

**Comment by nyasuto** [comment]
## 🔍 キャッシュ効果分析 - go.sum問題発見

### 問題の根本原因

PR #26のCI実行を分析した結果、キャッシュが期待通り効いていない主な原因を特定しました：

**Go依存関係キャッシュの問題:**
- ❌ ファイルが存在しない
- ❌ 外部依存関係がに定義されていない  
- ❌ のキャッシュが効果的に機能しない

### 実装した対応策

**1. CI設定の改善 (commit: 1b75192)**
```yaml
# Before: go.sumのみ参照（存在しない）
cache-dependency-path: go.sum

# After: go.modも含めた柔軟な設定
cache-dependency-path: |
  go.sum  
  go.mod
```

**2. Goツールキャッシュの拡張**
```yaml
path: |
  ~/go/bin          # ツールバイナリ
  ~/go/pkg/mod      # モジュールキャッシュ
key: ${{ runner.os }}-go-tools-${{ hashFiles('Makefile', 'go.mod') }}
```

**3. APTパッケージキャッシュの修正**
- 不安定なから公式に変更
- を直接キャッシュ

### 期待される効果

**現在の状況:**
- Goツールインストール: ~30-60秒/ジョブ
- APTパッケージ: ~15-30秒/ジョブ  
- 合計改善見込み: 30-50%の時間短縮

**将来的な改善（外部依存関係追加時）:**
- go.sum生成により、さらに大幅な時間短縮が期待される

### 次回CI実行での検証ポイント

- [ ] APTキャッシュの動作確認
- [ ] Goツール・モジュールキャッシュの効果測定
- [ ] 全体的な実行時間の改善確認

**Status:** ✅ 対応済み - PR #26で改善されたキャッシュ戦略をテスト中
